# Use the official PostgreSQL image
FROM postgres:latest
 
# Set environment variables for the database
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB employee_data

# Expose the PostgreSQL port
EXPOSE 5432
